In [1]:
# %load LOOCV.py
%matplotlib
from matplotlib import pyplot as plt
import lasio
from sklearn import preprocessing
import numpy as np
np.set_printoptions(threshold=np.inf)
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import openpyxl
from sklearn.svm import SVR
from sklearn.model_selection import LeaveOneOut
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn import tree
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
import random
from matplotlib.font_manager import *
import matplotlib.pyplot as plt

Using matplotlib backend: TkAgg


In [2]:
from model import one_cnn_model, three_cnn_model, bp_model, LinearRegression_model1, LinearRegression_model2
import model
import imp
imp.reload(model)
from model import one_cnn_model, three_cnn_model, bp_model, LinearRegression_model1, LinearRegression_model2

In [2]:
from DataSet import dataset_lab
import DataSet
import imp
imp.reload(DataSet)
from DataSet import dataset_lab

In [3]:
from Normalization import Normalization, Anti_Normalization, Normalization_lab, Anti_Normalization_lab
import Normalization
import imp
imp.reload(Normalization)
from Normalization import Normalization, Anti_Normalization, Normalization_lab, Anti_Normalization_lab

In [2]:
# 读取初始化相关数据
b = 6

data = dataset_lab(b)

保存[DTS, DT, RHOB, GR, GAS(real), GAS(log))

np.savetxt(r"C:\Users\Administrator\Projects\LongMaXi\unShuffle_data",data)

In [142]:
#画热力图
a=pd.DataFrame(data[:,0:-1]).corr()
import matplotlib.pyplot as plt
import seaborn as sns
plt.subplots(figsize=(9, 9))
sns.heatmap(a, annot=True, vmax=1, square=True, cmap="Blues", xticklabels=False, yticklabels=False, annot_kws={'size':12})
plt.show()

In [4]:
data = np.loadtxt(r"C:\Users\Administrator\Projects\LongMaXi\unShuffle_data")

OSError: C:\Users\Administrator\Projects\LongMaXi\unShuffle_data not found.

In [62]:
shuffle_data = data[:,[0,1,2, 4, 5]]
print(shuffle_data.shape)

(201, 5)


In [63]:
np.random.shuffle(shuffle_data)
print(shuffle_data.shape)

(201, 5)


In [64]:
model = LinearRegression()
shuffle_RHOB = shuffle_data[:, 2].reshape(-1, 1)
shuffle_GAS = shuffle_data[:, 3].reshape(-1, 1)
model.fit(shuffle_RHOB, shuffle_GAS)
score = model.score(shuffle_RHOB, shuffle_GAS)
ev = model.coef_  # 回归系数
inter = model.intercept_
shuffle_LR_GAS = model.predict(shuffle_RHOB).reshape(-1, 1)
#     print("yhat:", yhat)
#     print("yhat_array[test_index][0]:", yhat_array[test_index][0])
print("ev:", ev)
print("inter:", inter)

ev: [[-10.56499268]]
inter: [29.40776038]


In [65]:
Onefil_data = []
b = 1.6
for i in range(shuffle_data.shape[0]):
    if(-b< (shuffle_GAS[i] - shuffle_LR_GAS[i]) < b):
        Onefil_data.append(shuffle_data[i])
Onefil_data = np.array(Onefil_data)
print(Onefil_data.shape)

(179, 5)


In [66]:
Onefil_NL_data = Normalization_lab(Onefil_data)

(179, 5)


In [ ]:
#画热力图
a=pd.DataFrame(Onefil_NL_data[:,0:-1]).corr()
import matplotlib.pyplot as plt
import seaborn as sns
plt.subplots(figsize=(9, 9))
sns.heatmap(a, annot=True, vmax=1, square=True, cmap="Blues", xticklabels=False, yticklabels=False, annot_kws={'size':12})
plt.show()

In [ ]:
cnn

cnn

In [67]:
loo = LeaveOneOut()
Onefil_cnn =[]
Onefil_NL_input_data = Onefil_NL_data[:, 0: 3].reshape(-1, 1, 3)
Onefil_NL_output_data = Onefil_NL_data[:, 3].reshape(-1, 1, 1)
loo.get_n_splits(Onefil_NL_input_data)
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]
    Onefil_yhat, model, history = three_cnn_model(NL_train_X_data, NL_train_Y_data, NL_test_X_data, NL_test_Y_data, 32)
    NL_test_X_data = NL_test_X_data.reshape(1,-1)
    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat, Onefil_NL_data[2,-1].reshape(-1, 1))
    Onefil_cnn.append(Onefil_yhat)
Onefil_cnn = np.array(Onefil_cnn)

Model: "sequential_717"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1436 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1437 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_718 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1438 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1439 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_719 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_359 (Flatten)        (None, 64)             

Model: "sequential_721"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1452 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1453 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_726 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1454 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1455 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_727 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_363 (Flatten)        (None, 64)             

Model: "sequential_725"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1468 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1469 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_734 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1470 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1471 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_735 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_367 (Flatten)        (None, 64)             

Model: "sequential_729"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1484 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1485 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_742 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1486 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1487 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_743 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_371 (Flatten)        (None, 64)             

Model: "sequential_733"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1500 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1501 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_750 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1502 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1503 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_751 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_375 (Flatten)        (None, 64)             

Model: "sequential_737"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1516 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1517 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_758 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1518 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1519 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_759 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_379 (Flatten)        (None, 64)             

Model: "sequential_741"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1532 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1533 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_766 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1534 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1535 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_767 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_383 (Flatten)        (None, 64)             

Model: "sequential_745"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1548 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1549 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_774 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1550 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1551 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_775 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_387 (Flatten)        (None, 64)             

Model: "sequential_749"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1564 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1565 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_782 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1566 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1567 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_783 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_391 (Flatten)        (None, 64)             

Model: "sequential_753"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1580 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1581 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_790 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1582 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1583 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_791 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_395 (Flatten)        (None, 64)             

Model: "sequential_757"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1596 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1597 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_798 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1598 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1599 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_799 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_399 (Flatten)        (None, 64)             

Model: "sequential_761"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1612 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1613 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_806 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1614 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1615 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_807 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_403 (Flatten)        (None, 64)             

Model: "sequential_765"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1628 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1629 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_814 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1630 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1631 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_815 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_407 (Flatten)        (None, 64)             

Model: "sequential_769"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1644 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1645 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_822 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1646 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1647 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_823 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_411 (Flatten)        (None, 64)             

Model: "sequential_773"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1660 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1661 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_830 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1662 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1663 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_831 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_415 (Flatten)        (None, 64)             

Model: "sequential_777"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1676 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1677 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_838 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1678 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1679 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_839 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_419 (Flatten)        (None, 64)             

Model: "sequential_781"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1692 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1693 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_846 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1694 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1695 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_847 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_423 (Flatten)        (None, 64)             

Model: "sequential_785"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1708 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1709 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_854 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1710 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1711 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_855 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_427 (Flatten)        (None, 64)             

Model: "sequential_789"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1724 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1725 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_862 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1726 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1727 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_863 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_431 (Flatten)        (None, 64)             

Model: "sequential_793"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1740 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1741 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_870 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1742 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1743 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_871 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_435 (Flatten)        (None, 64)             

Model: "sequential_797"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1756 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1757 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_878 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1758 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1759 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_879 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_439 (Flatten)        (None, 64)             

Model: "sequential_801"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1772 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1773 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_886 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1774 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1775 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_887 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_443 (Flatten)        (None, 64)             

Model: "sequential_805"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1788 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1789 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_894 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1790 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1791 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_895 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_447 (Flatten)        (None, 64)             

Model: "sequential_809"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1804 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1805 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_902 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1806 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1807 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_903 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_451 (Flatten)        (None, 64)             

Model: "sequential_813"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1820 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1821 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_910 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1822 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1823 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_911 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_455 (Flatten)        (None, 64)             

Model: "sequential_817"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1836 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1837 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_918 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1838 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1839 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_919 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_459 (Flatten)        (None, 64)             

Model: "sequential_821"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1852 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1853 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_926 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1854 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1855 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_927 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_463 (Flatten)        (None, 64)             

Model: "sequential_825"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1868 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1869 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_934 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1870 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1871 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_935 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_467 (Flatten)        (None, 64)             

Model: "sequential_829"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1884 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1885 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_942 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1886 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1887 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_943 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_471 (Flatten)        (None, 64)             

Model: "sequential_833"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1900 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1901 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_950 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1902 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1903 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_951 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_475 (Flatten)        (None, 64)             

Model: "sequential_837"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1916 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1917 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_958 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1918 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1919 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_959 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_479 (Flatten)        (None, 64)             

Model: "sequential_841"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1932 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1933 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_966 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1934 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1935 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_967 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_483 (Flatten)        (None, 64)             

Model: "sequential_845"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1948 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1949 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_974 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1950 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1951 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_975 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_487 (Flatten)        (None, 64)             

Model: "sequential_849"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1964 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1965 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_982 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1966 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1967 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_983 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_491 (Flatten)        (None, 64)             

Model: "sequential_853"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1980 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1981 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_990 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1982 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1983 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_991 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_495 (Flatten)        (None, 64)             

Model: "sequential_857"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1996 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_1997 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_998 (MaxPoolin (None, 32, 2)             0         
_________________________________________________________________
conv1d_1998 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_1999 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_999 (MaxPoolin (None, 64, 1)             0         
_________________________________________________________________
flatten_499 (Flatten)        (None, 64)             

Model: "sequential_861"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2012 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2013 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1006 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2014 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2015 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1007 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_503 (Flatten)        (None, 64)             

Model: "sequential_865"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2028 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2029 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1014 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2030 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2031 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1015 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_507 (Flatten)        (None, 64)             

Model: "sequential_869"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2044 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2045 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1022 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2046 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2047 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1023 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_511 (Flatten)        (None, 64)             

Model: "sequential_873"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2060 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2061 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1030 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2062 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2063 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1031 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_515 (Flatten)        (None, 64)             

Model: "sequential_877"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2076 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2077 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1038 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2078 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2079 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1039 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_519 (Flatten)        (None, 64)             

Model: "sequential_881"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2092 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2093 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1046 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2094 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2095 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1047 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_523 (Flatten)        (None, 64)             

Model: "sequential_885"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2108 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2109 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1054 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2110 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2111 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1055 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_527 (Flatten)        (None, 64)             

Model: "sequential_889"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2124 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2125 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1062 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2126 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2127 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1063 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_531 (Flatten)        (None, 64)             

Model: "sequential_893"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2140 (Conv1D)         (None, 32, 3)             96        
_________________________________________________________________
conv1d_2141 (Conv1D)         (None, 32, 3)             2080      
_________________________________________________________________
max_pooling1d_1070 (MaxPooli (None, 32, 2)             0         
_________________________________________________________________
conv1d_2142 (Conv1D)         (None, 64, 2)             4160      
_________________________________________________________________
conv1d_2143 (Conv1D)         (None, 64, 2)             8256      
_________________________________________________________________
max_pooling1d_1071 (MaxPooli (None, 64, 1)             0         
_________________________________________________________________
flatten_535 (Flatten)        (None, 64)             

bp

In [68]:
Onefil_NL_input_data = Onefil_NL_data[:, 0: 3].reshape(-1, 1, 3)
Onefil_NL_output_data = Onefil_NL_data[:, 3].reshape(-1, 1, 1)
loo.get_n_splits(Onefil_NL_input_data)
Onefil_bp =[]
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]
    Onefil_yhat, model, history = bp_model(NL_train_X_data, NL_train_Y_data, NL_test_X_data, NL_test_Y_data)
    NL_test_X_data = NL_test_X_data.reshape(1,-1)
    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat,Onefil_NL_data[2,-1].reshape(-1, 1))
    Onefil_bp.append(Onefil_yhat)
Onefil_bp= np.array(Onefil_bp).reshape(-1, 1)

rf

In [69]:
Onefil_NL_input_data = Onefil_NL_data[:, 0:3]
print(Onefil_NL_input_data.shape)
Onefil_NL_output_data = Onefil_NL_data[:,3]

(179, 3)


In [70]:
x_len = Onefil_NL_input_data.shape[1]

In [71]:
loo = LeaveOneOut()
loo.get_n_splits(Onefil_NL_input_data)
Onefil_rf =[]
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]

    NL_train_X_data, NL_test_X_data = NL_train_X_data.reshape(-1, x_len), NL_test_X_data.reshape(-1, x_len)
    NL_test_X_data = NL_test_X_data.reshape(-1, x_len)
    rfr = RandomForestRegressor(n_estimators = 128, min_samples_leaf = 14, random_state=13)
    Onefil_yhat = rfr.fit(NL_train_X_data,NL_train_Y_data).predict(NL_test_X_data).reshape(-1, 1)

    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat, Onefil_NL_data[2,-1].reshape(-1, 1))
    Onefil_rf.append(Onefil_yhat)
Onefil_rf= np.array(Onefil_rf).reshape(-1, 1)
print(Onefil_rf.shape)

(179, 1)


DT

In [72]:
loo = LeaveOneOut()
loo.get_n_splits(Onefil_NL_input_data)
Onefil_dt =[]
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]

    NL_train_X_data, NL_test_X_data = NL_train_X_data.reshape(-1, x_len), NL_test_X_data.reshape(-1, x_len)
    NL_test_X_data = NL_test_X_data.reshape(-1, x_len)
    dtr = tree.DecisionTreeRegressor(max_depth = 20, min_samples_leaf = 20, random_state=13)
    Onefil_yhat = dtr.fit(NL_train_X_data, NL_train_Y_data).predict(NL_test_X_data).reshape(-1, 1)

    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat,Onefil_NL_data[2,-1].reshape(-1, 1))
    Onefil_dt.append(Onefil_yhat)
Onefil_dt= np.array(Onefil_dt).reshape(-1, 1)

SVR

In [73]:
loo = LeaveOneOut()
loo.get_n_splits(Onefil_NL_input_data)
Onefil_svr =[]
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]

    NL_train_X_data, NL_test_X_data = NL_train_X_data.reshape(-1, x_len), NL_test_X_data.reshape(-1,x_len)
    NL_test_X_data = NL_test_X_data.reshape(-1, x_len)
    svr_rbf = SVR(kernel='rbf', C=1e2, gamma = 0.4)
    Onefil_yhat = svr_rbf.fit(NL_train_X_data, NL_train_Y_data).predict(NL_test_X_data).reshape(-1, 1)
    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat, Onefil_NL_data[2,-1].reshape(-1, 1))
    # Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat)
    Onefil_svr.append(Onefil_yhat)
#     print("yhat:", yhat)
#     print("yhat_array[test_index][0]:", yhat_array[test_index][0])
Onefil_svr= np.array(Onefil_svr).reshape(-1, 1)
print(Onefil_svr.shape)

(179, 1)


In [81]:
print(Onefil_svr)

[[ 0.56090568]
 [ 0.28843033]
 [ 1.71521853]
 [ 3.36632795]
 [ 1.92882423]
 [ 3.38253538]
 [ 2.20764773]
 [ 5.21866301]
 [ 3.11397503]
 [ 2.67267537]
 [ 2.38826828]
 [ 3.86739008]
 [ 2.01627534]
 [ 0.91417188]
 [ 1.46069291]
 [ 2.34097788]
 [ 1.96921572]
 [ 2.16314448]
 [ 1.03149208]
 [ 3.5022595 ]
 [ 1.94041696]
 [ 4.15207546]
 [ 2.31182218]
 [ 2.32440201]
 [ 3.91495223]
 [-0.03375214]
 [ 4.17053046]
 [ 2.3926351 ]
 [ 2.73932478]
 [ 2.42309285]
 [ 2.00586607]
 [ 0.2257898 ]
 [ 3.67812836]
 [ 2.61947937]
 [ 0.43426083]
 [ 0.85176439]
 [ 2.38205128]
 [ 0.74214117]
 [ 3.4186737 ]
 [ 1.70816878]
 [ 0.86685715]
 [ 0.11623341]
 [ 1.6094211 ]
 [ 3.09176465]
 [ 1.5924136 ]
 [ 0.23005385]
 [ 2.58840808]
 [ 2.59999874]
 [ 2.49863911]
 [ 2.52181846]
 [ 2.36869412]
 [ 2.98582328]
 [ 4.53401386]
 [ 0.82510712]
 [ 2.41730009]
 [ 2.20590768]
 [ 2.87378266]
 [ 2.30807081]
 [ 2.91232758]
 [ 2.22821858]
 [ 1.59730839]
 [ 1.89565173]
 [ 2.03218794]
 [ 1.7457787 ]
 [ 1.1590686 ]
 [ 2.76389711]
 [ 2.82147

In [87]:
excel = np.hstack(((Onefil_data[:,3]).reshape(-1,1),Onefil_svr, Onefil_dt, Onefil_rf, 
                  Onefil_bp.reshape(-1,1), Onefil_cnn.reshape(-1, 1)))
print(excel)   


[[ 0.4667      0.56090568  0.54235493  0.60854014  0.31635404  0.4902363 ]
 [ 0.31        0.28843033  0.54795136  0.60060659  0.57319949  0.3164592 ]
 [ 0.6164      1.71521853  1.36306512  1.60569935  1.75528966  2.04172711]
 [ 2.7         3.36632795  3.79417039  3.77796681  3.43520107  3.39185067]
 [ 0.86711825  1.92882423  2.14277737  2.16128255  2.61103656  2.72952201]
 [ 2.91        3.38253538  3.78667039  3.75869678  3.35556068  3.19243269]
 [ 2.28356167  2.20764773  2.34317677  2.14608587  2.3626722   2.22083026]
 [ 3.9         5.21866301  3.75131324  3.75685506  4.38332743  5.27307175]
 [ 4.32633246  3.11397503  3.73608709  3.34299076  3.08838432  3.30082977]
 [ 3.12        2.67267537  2.82471756  2.72306769  2.69029774  2.81503759]
 [ 2.30508386  2.38826828  2.54684182  2.330354    2.59747537  2.71850896]
 [ 3.82588478  3.86739008  3.75396022  3.73489008  3.75445388  3.57546473]
 [ 1.63673935  2.01627534  1.32527477  1.76547908  2.13367736  1.73713774]
 [ 1.7210667   0.91417188

LR

In [40]:
loo = LeaveOneOut()
loo.get_n_splits(Onefil_NL_input_data)
Onefil_lr =[]
for train_index, test_index in loo.split(Onefil_NL_input_data):
    NL_train_X_data, NL_test_X_data = Onefil_NL_input_data[train_index], Onefil_NL_input_data[test_index]
    NL_train_Y_data, NL_test_Y_data = Onefil_NL_output_data[train_index], Onefil_NL_output_data[test_index]

    NL_train_X_data, NL_test_X_data = NL_train_X_data.reshape(-1, x_len), NL_test_X_data.reshape(-1, x_len)
    NL_test_X_data = NL_test_X_data.reshape(-1, x_len)
    Onefil_yhat, model, score, ev  = LinearRegression_model1(NL_train_X_data, NL_train_Y_data, NL_test_X_data, NL_test_Y_data)
    Onefil_yhat = Anti_Normalization_lab(Onefil_data, NL_test_X_data, Onefil_yhat, Onefil_NL_data[2,-1].reshape(-1, 1))
    Onefil_lr.append(Onefil_yhat)
#     print("yhat:", yhat)
#     print("yhat_array[test_index][0]:", yhat_array[test_index][0])
Onefil_lr= np.array(Onefil_lr).reshape(-1, 1)

In [89]:
print('相关系数: ', np.corrcoef(data[:,0], data[:, 4]))
# a = Onefil_lr/4+Onefil_cnn.reshape(-1, 1)/4+Onefil_svr.reshape(-1, 1)/4+Onefil_bp.reshape(-1, 1)/4
# print(a.shape)
# print("a_Aim:", np.hstack((Onefil_Aim, Onefil_svr.reshape(-1, 1))))
# int('mse: ', mean_squared_error())
print('R2: ', r2_score(Onefil_data[:,3], Onefil_svr.reshape(-1, 1)))
print('mse: ', mean_squared_error(Onefil_data[:,3], Onefil_cnn.reshape(-1, 1)))

相关系数:  [[ 1.         -0.42117273]
 [-0.42117273  1.        ]]
R2:  0.7063834814070289
mse:  0.5211612390515903


In [25]:
plt.figure(figsize=(20,10))
plt.plot(Onefil_data[:,4], '-', linewidth=2)
plt.plot(Onefil_lr, '-', linewidth=2)
plt.xticks(fontsize=14);
plt.yticks(fontsize=14);
plt.show

<function matplotlib.pyplot.show>

测井曲线

In [24]:
plt.figure(figsize=(20, 10))
plt.plot(Onefil_data[:,4], '-', linewidth=2)
plt.plot(Onefil_data[:,5], '-', linewidth=2)
plt.xticks(fontsize=14);
plt.yticks(fontsize=14);
plt.show

<function matplotlib.pyplot.show>

预测曲线

In [302]:
fig = plt.figure(figsize=(20,5))
plt.plot(Onefil_data[:,3], '-', linewidth=2, label='Core_value')
plt.plot(Onefil_svr, '-', linewidth=2, label='DT_predict_value')
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.show()

In [60]:
fig_1 = plt.figure(figsize=(20, 10))  # 作图画布大小(每循环一次，就会建立新的画布）
ax = fig_1.add_subplot( 5, 1,1)
ax.plot(Onefil_data[:,3], '-', linewidth=2)
ax.plot(Onefil_svr, '-', linewidth=2)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.yticks(range(0,6,2))
ax = fig_1.add_subplot(5, 1, 2)
ax.plot(Onefil_data[:,3], '-', linewidth=2)
ax.plot(Onefil_dt, '-', linewidth=2)

plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.yticks(range(0,6,2))
ax = fig_1.add_subplot(5, 1, 3)
ax.plot(Onefil_data[:,3], '-', linewidth=2)
ax.plot(Onefil_rf, '-', linewidth=2)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.yticks(range(0,6,2))
ax = fig_1.add_subplot(5, 1, 4)
ax.plot(Onefil_data[:,3], '-', linewidth=2)
ax.plot(Onefil_bp, '-', linewidth=2)
plt.yticks(range(0,6,2))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
ax = fig_1.add_subplot(5, 1, 5)
ax.plot(Onefil_data[:,3], '-', linewidth=2)
ax.plot(Onefil_cnn.reshape(-1, 1), '-', linewidth=2)
plt.yticks(range(0,6,2))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
#     # plt.savefig(r"D:\software\pycharm\PyCharm 1319.3.3\projects\predict_GASV\结果\onewey\图片\两口井3to5\onecon/" + name + ".png")
#     plt.savefig("lab_bp_loocv_carve_predict")

plt.show()

散点图

In [202]:
fig_2 = plt.figure(figsize=(20, 5))
fig_2.add_subplot(1, 3, 1)
plt.scatter(shuffle_data[:,1], shuffle_data[:,4],  s = 16)
plt.scatter(Onefil_data[:,1], Onefil_data[:,4], color = '#FF8C00', s = 14)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

fig_2.add_subplot(1, 3, 2)
plt.scatter(shuffle_data[:,0], shuffle_data[:,4], s = 16)
plt.scatter(Onefil_data[:,0], Onefil_data[:,4], color = '#FF8C00',s = 14)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

fig_2.add_subplot(1, 3, 3)
plt.scatter(shuffle_RHOB, shuffle_GAS, s = 16)
plt.scatter(Onefil_data[:,2], Onefil_data[:,4], color = '#FF8C00', s = 14)
plt.plot(shuffle_RHOB, shuffle_LR_GAS + 1.6, color = 'black')
plt.plot(shuffle_RHOB, shuffle_LR_GAS - 1.6, color = 'black')
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

(array([-2.,  0.,  2.,  4.,  6.,  8., 10.]),
 <a list of 7 Text yticklabel objects>)